---
- name: Set Up TargetNode
  hosts: 18.183.191.132
  become: yes
  tasks:
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
        lock_timeout: 180

  roles:
    - nginx
