---
# tasks file for rails
- name: Check if rails is installed
  ansible.builtin.command:
    cmd: rails -v
  register: rails_check
  ignore_errors: true
  changed_when: false

- name: Install rails
  ansible.builtin.shell:
    cmd: /bin/bash -lc "gem install rails -v {{rails_version}}"
  register: rails_install
  when: rails_check.failed

#- name: レジスタ確認_rails_install
#  ansible.builtin.debug:
#    var: rails_install
